version: "3"

services:
  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    container_name: d_nuxtjs
    volumes:
      - ./app/:/src/
    ports:
      - "3000:3000"
    command:
      "npm run dev"
    network_mode: host
