version: "2"

services:
  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    container_name: d_nuxtjs
    volumes:
      - ./app/:/src/
    ports:
      - "3000:3000"
    mem_limit: 1000m
    command:
      "npm run dev"
    network_mode: host
    environment:
      VIRTUAL_HOST: "nuxt.vm"
      VIRTUAL_PORT: "3000"
